//! Exact physics handoff reports for retained BREP shells.
//!
//! `hyperbrep` owns retained boundary topology and exact surface evidence;
//! `hyperphysics` owns material density, mass properties, and physical
//! interpretation. This module therefore consumes the shared exact triangle
//! handoff and packages physics-specific shape, fixture, and mass reports.

use hyperphysics::{
    ClosedTriangleMesh3, ExactFixture3, ExactMaterial, FixtureId, MassPropertyReport3,
    PhysicsError, PhysicsShape3, Triangle3, Vector3,
};
use hyperreal::Real;

use crate::solid::BrepSolidReadinessReport;
use crate::topology::BrepShell;
use crate::triangle::{BrepExactTriangleMeshHandoffReport, BrepTriangleMeshBlocker};

/// Explicit blocker for exact BREP-to-physics mass handoff.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum BrepPhysicsMassBlocker {
    /// Solid readiness did not accept the retained shell.
    SolidReadinessNotReady,
    /// Mass handoff currently accepts only simple outer loops.
    InnerLoopsUnsupported,
    /// Exact face triangulation rejected a trim profile.
    TriangulationRejected,
    /// A face referenced missing or unready retained surface data.
    SurfaceNotReady,
    /// A face loop has fewer than three coedges.
    DegenerateLoop,
    /// A coedge references an edge id not present in the shell.
    MissingEdge,
    /// A referenced edge starts and ends at the same vertex.
    DegenerateEdge,
    /// A referenced edge points at a vertex id not present in the shell.
    MissingVertex,
    /// Consecutive oriented coedges do not form a closed vertex chain.
    BrokenLoopChain,
    /// Exact physics mesh construction rejected the generated triangles.
    PhysicsMeshRejected,
    /// `hyperphysics` rejected the density or could not certify mass integrals.
    PhysicsMassRejected,
}

/// Explicit blocker for exact BREP-to-physics shape handoff.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum BrepPhysicsShapeBlocker {
    /// Solid readiness did not accept the retained shell.
    SolidReadinessNotReady,
    /// Shape handoff currently accepts only simple outer loops.
    InnerLoopsUnsupported,
    /// Exact face triangulation rejected a trim profile.
    TriangulationRejected,
    /// A face referenced missing or unready retained surface data.
    SurfaceNotReady,
    /// A face loop has fewer than three coedges.
    DegenerateLoop,
    /// A coedge references an edge id not present in the shell.
    MissingEdge,
    /// A referenced edge starts and ends at the same vertex.
    DegenerateEdge,
    /// A referenced edge points at a vertex id not present in the shell.
    MissingVertex,
    /// Consecutive oriented coedges do not form a closed vertex chain.
    BrokenLoopChain,
    /// Exact physics mesh construction rejected the generated triangles.
    PhysicsMeshRejected,
    /// The requested fixture id was rejected by `hyperphysics`.
    PhysicsFixtureIdRejected,
}

/// Exact physics shape handoff for one retained BREP shell.
#[derive(Clone, Debug, PartialEq)]
pub struct BrepPhysicsShapeHandoffReport {
    /// Solid-readiness evidence replayed before generating physics triangles.
    pub solid: BrepSolidReadinessReport,
    /// Reusable exact BREP triangle handoff consumed by this physics bridge.
    pub triangle_mesh: BrepExactTriangleMeshHandoffReport,
    /// Number of retained faces scanned.
    pub face_count: usize,
    /// Number of triangle facets generated by exact face triangulation.
    pub triangle_count: usize,
    /// Exact physics triangle mesh, when accepted.
    pub mesh: Option<ClosedTriangleMesh3>,
    /// Exact physics shape, when accepted.
    pub shape: Option<PhysicsShape3>,
    /// Physics error that blocked mesh construction, when available.
    pub physics_error: Option<PhysicsError>,
    /// Explicit blockers.
    pub blockers: Vec<BrepPhysicsShapeBlocker>,
    /// Whether exact BREP evidence was accepted by the physics shape boundary.
    pub exact_physics_shape_ready: bool,
}

/// Exact physics fixture handoff for one retained BREP shell and material.
#[derive(Clone, Debug, PartialEq)]
pub struct BrepPhysicsFixtureHandoffReport {
    /// Shape handoff used to build the fixture.
    pub shape_handoff: BrepPhysicsShapeHandoffReport,
    /// Exact fixture, when shape, id, and material evidence were accepted.
    pub fixture: Option<ExactFixture3>,
    /// Physics error that blocked fixture construction, when available.
    pub physics_error: Option<PhysicsError>,
    /// Explicit blockers.
    pub blockers: Vec<BrepPhysicsShapeBlocker>,
    /// Whether exact BREP evidence and material evidence produced a fixture.
    pub exact_physics_fixture_ready: bool,
}

/// Exact physics mass-property handoff for one retained BREP shell.
#[derive(Clone, Debug, PartialEq)]
pub struct BrepPhysicsMassHandoffReport {
    /// Solid-readiness evidence replayed before generating physics triangles.
    pub solid: BrepSolidReadinessReport,
    /// Reusable exact BREP triangle handoff consumed by this physics bridge.
    pub triangle_mesh: BrepExactTriangleMeshHandoffReport,
    /// Number of retained faces scanned.
    pub face_count: usize,
    /// Number of triangle facets generated by exact face triangulation.
    pub triangle_count: usize,
    /// Density requested by the caller.
    pub density: Real,
    /// Exact physics mass-property report, when accepted.
    pub mass_properties: Option<MassPropertyReport3>,
    /// Physics error that blocked mesh or mass construction, when available.
    pub physics_error: Option<PhysicsError>,
    /// Explicit blockers.
    pub blockers: Vec<BrepPhysicsMassBlocker>,
    /// Whether exact BREP evidence was accepted by the physics mass boundary.
    pub exact_physics_mass_ready: bool,
}

impl BrepPhysicsShapeHandoffReport {
    /// Build an exact physics shape from retained BREP shell evidence.
    ///
    /// The generated shape is a `hyperphysics::ClosedTriangleMesh3` wrapped in
    /// `PhysicsShape3`. It consumes `BrepExactTriangleMeshHandoffReport`, so
    /// physics, voxel, export, and diagnostic consumers can share one exact
    /// BREP triangle-lowering boundary. Unsupported holes, broken loops, and
    /// construction failures stay named blockers instead of being repaired by
    /// tolerance.
    pub fn from_shell(shell: &BrepShell) -> Self {
        let build = build_physics_mesh(shell);
        let shape = build
            .mesh
            .as_ref()
            .map(|mesh| PhysicsShape3::closed_triangle_mesh(mesh.clone()));
        let exact_physics_shape_ready = build.blockers.is_empty() && shape.is_some();
        Self {
            solid: build.solid,
            triangle_mesh: build.triangle_mesh,
            face_count: build.face_count,
            triangle_count: build.triangle_count,
            mesh: build.mesh,
            shape,
            physics_error: build.physics_error,
            blockers: build.blockers,
            exact_physics_shape_ready,
        }
    }
}

impl BrepPhysicsFixtureHandoffReport {
    /// Build an exact physics fixture from retained BREP shell and material.
    ///
    /// Material validation remains owned by `hyperphysics::ExactMaterial`; this
    /// handoff only combines a certified exact BREP-derived shape, fixture id,
    /// and already-validated material into a fixture carrier for downstream
    /// engines or physics reports.
    pub fn from_shell_material(
        shell: &BrepShell,
        fixture_id: impl Into<String>,
        material: ExactMaterial,
    ) -> Self {
        let shape_handoff = BrepPhysicsShapeHandoffReport::from_shell(shell);
        let mut blockers = shape_handoff.blockers.clone();
        let mut physics_error = shape_handoff.physics_error.clone();
        let fixture = if let Some(shape) = shape_handoff.shape.clone() {
            match FixtureId::new(fixture_id) {
                Ok(id) if blockers.is_empty() => Some(ExactFixture3::new(id, shape, material)),
                Ok(_) => None,
                Err(error) => {
                    blockers.push(BrepPhysicsShapeBlocker::PhysicsFixtureIdRejected);
                    physics_error = Some(error);
                    None
                }
            }
        } else {
            None
        };
        let exact_physics_fixture_ready = blockers.is_empty() && fixture.is_some();
        Self {
            shape_handoff,
            fixture,
            physics_error,
            blockers,
            exact_physics_fixture_ready,
        }
    }
}

impl BrepPhysicsMassHandoffReport {
    /// Build exact uniform-density physics mass properties from a retained shell.
    ///
    /// The shell first replays through exact BREP solid and triangle handoff
    /// gates. Mass-property integration is delegated to `hyperphysics`; this
    /// module does not infer missing trims, heal loops, or lower coordinates to
    /// floats.
    pub fn from_shell_density(shell: &BrepShell, density: Real) -> Self {
        let build = build_physics_mesh(shell);
        let solid = build.solid;
        let triangle_mesh = build.triangle_mesh;
        let mut blockers = Vec::new();
        blockers.extend(build.blockers.iter().map(shape_to_mass_blocker));
        let mut physics_error = build.physics_error;
        let mass_properties = if blockers.is_empty() {
            match build.mesh {
                Some(mesh) => match mesh.uniform_density_mass_properties(density.clone()) {
                    Ok(report) => Some(report),
                    Err(error) => {
                        blockers.push(BrepPhysicsMassBlocker::PhysicsMassRejected);
                        physics_error = Some(error);
                        None
                    }
                },
                None => None,
            }
        } else {
            None
        };
        let exact_physics_mass_ready = blockers.is_empty() && mass_properties.is_some();

        Self {
            solid,
            triangle_mesh,
            face_count: shell.faces.len(),
            triangle_count: build.triangle_count,
            density,
            mass_properties,
            physics_error,
            blockers,
            exact_physics_mass_ready,
        }
    }
}

impl BrepShell {
    /// Replay this retained shell as an exact physics shape.
    pub fn physics_shape_handoff_report(&self) -> BrepPhysicsShapeHandoffReport {
        BrepPhysicsShapeHandoffReport::from_shell(self)
    }

    /// Replay this retained shell as an exact physics fixture with material.
    pub fn physics_fixture_handoff_report(
        &self,
        fixture_id: impl Into<String>,
        material: ExactMaterial,
    ) -> BrepPhysicsFixtureHandoffReport {
        BrepPhysicsFixtureHandoffReport::from_shell_material(self, fixture_id, material)
    }

    /// Replay this retained shell as exact uniform-density physics mass evidence.
    pub fn physics_mass_handoff_report(&self, density: Real) -> BrepPhysicsMassHandoffReport {
        BrepPhysicsMassHandoffReport::from_shell_density(self, density)
    }
}

struct PhysicsMeshBuild {
    solid: BrepSolidReadinessReport,
    triangle_mesh: BrepExactTriangleMeshHandoffReport,
    face_count: usize,
    triangle_count: usize,
    mesh: Option<ClosedTriangleMesh3>,
    physics_error: Option<PhysicsError>,
    blockers: Vec<BrepPhysicsShapeBlocker>,
}

fn build_physics_mesh(shell: &BrepShell) -> PhysicsMeshBuild {
    let triangle_mesh = shell.exact_triangle_mesh_handoff_report();
    let solid = triangle_mesh.solid.clone();
    let mut blockers = triangle_mesh
        .blockers
        .iter()
        .map(triangle_to_shape_blocker)
        .collect::<Vec<_>>();
    let triangles = triangle_mesh
        .triangles
        .iter()
        .map(|triangle| {
            Triangle3::new([
                vector_from_point(&triangle.vertices[0]),
                vector_from_point(&triangle.vertices[1]),
                vector_from_point(&triangle.vertices[2]),
            ])
        })
        .collect::<Vec<_>>();
    let triangle_count = triangle_mesh.triangle_count;
    let mut physics_error = None;
    let mesh = if blockers.is_empty() {
        match ClosedTriangleMesh3::new(triangles) {
            Ok(mesh) => Some(mesh),
            Err(error) => {
                blockers.push(BrepPhysicsShapeBlocker::PhysicsMeshRejected);
                physics_error = Some(error);
                None
            }
        }
    } else {
        None
    };

    PhysicsMeshBuild {
        solid,
        triangle_mesh,
        face_count: shell.faces.len(),
        triangle_count,
        mesh,
        physics_error,
        blockers,
    }
}

fn shape_to_mass_blocker(blocker: &BrepPhysicsShapeBlocker) -> BrepPhysicsMassBlocker {
    match blocker {
        BrepPhysicsShapeBlocker::SolidReadinessNotReady => {
            BrepPhysicsMassBlocker::SolidReadinessNotReady
        }
        BrepPhysicsShapeBlocker::InnerLoopsUnsupported => {
            BrepPhysicsMassBlocker::InnerLoopsUnsupported
        }
        BrepPhysicsShapeBlocker::TriangulationRejected => {
            BrepPhysicsMassBlocker::TriangulationRejected
        }
        BrepPhysicsShapeBlocker::SurfaceNotReady => BrepPhysicsMassBlocker::SurfaceNotReady,
        BrepPhysicsShapeBlocker::DegenerateLoop => BrepPhysicsMassBlocker::DegenerateLoop,
        BrepPhysicsShapeBlocker::MissingEdge => BrepPhysicsMassBlocker::MissingEdge,
        BrepPhysicsShapeBlocker::DegenerateEdge => BrepPhysicsMassBlocker::DegenerateEdge,
        BrepPhysicsShapeBlocker::MissingVertex => BrepPhysicsMassBlocker::MissingVertex,
        BrepPhysicsShapeBlocker::BrokenLoopChain => BrepPhysicsMassBlocker::BrokenLoopChain,
        BrepPhysicsShapeBlocker::PhysicsMeshRejected
        | BrepPhysicsShapeBlocker::PhysicsFixtureIdRejected => {
            BrepPhysicsMassBlocker::PhysicsMeshRejected
        }
    }
}

fn triangle_to_shape_blocker(blocker: &BrepTriangleMeshBlocker) -> BrepPhysicsShapeBlocker {
    match blocker {
        BrepTriangleMeshBlocker::SolidReadinessNotReady => {
            BrepPhysicsShapeBlocker::SolidReadinessNotReady
        }
        BrepTriangleMeshBlocker::InnerLoopsUnsupported => {
            BrepPhysicsShapeBlocker::InnerLoopsUnsupported
        }
        BrepTriangleMeshBlocker::TriangulationRejected => {
            BrepPhysicsShapeBlocker::TriangulationRejected
        }
        BrepTriangleMeshBlocker::MissingSurface | BrepTriangleMeshBlocker::SurfaceFrameNotReady => {
            BrepPhysicsShapeBlocker::SurfaceNotReady
        }
        BrepTriangleMeshBlocker::DegenerateLoop => BrepPhysicsShapeBlocker::DegenerateLoop,
        BrepTriangleMeshBlocker::MissingEdge => BrepPhysicsShapeBlocker::MissingEdge,
        BrepTriangleMeshBlocker::DegenerateEdge => BrepPhysicsShapeBlocker::DegenerateEdge,
        BrepTriangleMeshBlocker::MissingVertex => BrepPhysicsShapeBlocker::MissingVertex,
        BrepTriangleMeshBlocker::BrokenLoopChain => BrepPhysicsShapeBlocker::BrokenLoopChain,
    }
}

fn vector_from_point(point: &hyperlimit::Point3) -> Vector3 {
    Vector3::new([point.x.clone(), point.y.clone(), point.z.clone()])
}
