//! Retained-BREP exact triangle mesh handoff.
//!
//! This module lowers exact-ready planar shell faces into exact triangles while
//! keeping the source BREP as the authority. It is not a tessellator adapter and
//! it does not promote triangles back into topology; it is a reusable handoff
//! surface for physics, voxelization, mesh export, and diagnostics.

use std::collections::BTreeMap;

use hyperlimit::{Point2, Point3};

use crate::solid::BrepSolidReadinessReport;
use crate::surface::BrepSurfaceKind;
use crate::topology::{
    BrepCoedge, BrepEdge, BrepEdgeOrientation, BrepFaceId, BrepShell, BrepVertexId,
};

/// Explicit blocker for retained-BREP exact triangle lowering.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum BrepTriangleMeshBlocker {
    /// Solid readiness did not accept the retained shell.
    SolidReadinessNotReady,
    /// This first exact lowering accepts only simple outer loops.
    InnerLoopsUnsupported,
    /// Exact polygon triangulation rejected a face trim profile.
    TriangulationRejected,
    /// A face references a missing retained surface.
    MissingSurface,
    /// A face references a surface without an exact parameter frame.
    SurfaceFrameNotReady,
    /// A face loop has fewer than three coedges.
    DegenerateLoop,
    /// A coedge references an edge id not present in the shell.
    MissingEdge,
    /// A referenced edge starts and ends at the same vertex.
    DegenerateEdge,
    /// A referenced edge points at a vertex id not present in the shell.
    MissingVertex,
    /// Consecutive oriented coedges do not form a closed vertex chain.
    BrokenLoopChain,
}

/// Exact triangle produced from retained BREP vertices.
#[derive(Clone, Debug, PartialEq)]
pub struct BrepExactTriangle3 {
    /// Triangle vertices in oriented shell order.
    pub vertices: [Point3; 3],
}

/// Exact triangle mesh handoff derived from retained BREP shell loops.
#[derive(Clone, Debug, PartialEq)]
pub struct BrepExactTriangleMeshHandoffReport {
    /// Solid-readiness evidence replayed before triangle lowering.
    pub solid: BrepSolidReadinessReport,
    /// Number of retained faces scanned.
    pub face_count: usize,
    /// Number of triangle facets generated by fan triangulation.
    pub triangle_count: usize,
    /// Exact triangles produced from retained vertices.
    pub triangles: Vec<BrepExactTriangle3>,
    /// Whether triangles remain a downstream handoff, not source topology.
    pub retained_brep_source: bool,
    /// Whether the handoff is a lossy or preview-derived mesh.
    pub lossy_or_preview_mesh: bool,
    /// Explicit blockers.
    pub blockers: Vec<BrepTriangleMeshBlocker>,
    /// Whether exact triangles are ready for downstream consumers.
    pub exact_triangle_mesh_ready: bool,
}

impl BrepExactTriangleMeshHandoffReport {
    /// Build exact triangles from retained shell evidence.
    ///
    /// The shell first passes through `BrepSolidReadinessReport`; accepted face
    /// loops are then projected through their retained exact surface frame,
    /// triangulated by `hypertri`'s exact earcut path, and lifted back to 3D.
    /// This follows Yap, "Towards Exact Geometric Computation,"
    /// *Computational Geometry* 7.1-2 (1997): downstream consumers receive
    /// explicit exact evidence and blockers instead of hidden tolerance repair.
    /// BREP loop traversal follows Mäntylä, *An Introduction to Solid Modeling*
    /// (1988), and the exact ear-removal basis follows Meisters, "Polygons
    /// Have Ears," *American Mathematical Monthly* 82(6), 1975.
    pub fn from_shell(shell: &BrepShell) -> Self {
        let solid = shell.solid_readiness_report(None);
        let mut blockers = Vec::new();
        if !solid.exact_solid_boundary_ready {
            blockers.push(BrepTriangleMeshBlocker::SolidReadinessNotReady);
        }

        let edge_by_id = shell
            .edges
            .iter()
            .map(|edge| (edge.id, *edge))
            .collect::<BTreeMap<_, _>>();
        let vertex_by_id = shell
            .vertices
            .iter()
            .map(|vertex| (vertex.id, vertex))
            .collect::<BTreeMap<_, _>>();

        let surface_by_id = shell
            .surfaces
            .iter()
            .map(|surface| (surface.id, surface))
            .collect::<BTreeMap<_, _>>();
        let mut triangles = Vec::new();
        for face in &shell.faces {
            let Some(surface) = surface_by_id.get(&face.surface) else {
                blockers.push(BrepTriangleMeshBlocker::MissingSurface);
                continue;
            };
            if let Some(face_triangles) = triangulate_face(
                face.id,
                surface,
                &face.outer.coedges,
                face.inner.iter().map(|loop_| loop_.coedges.as_slice()),
                &edge_by_id,
                &vertex_by_id,
                &mut blockers,
            ) {
                triangles.extend(face_triangles);
            }
        }

        let triangle_count = triangles.len();
        let exact_triangle_mesh_ready = blockers.is_empty() && triangle_count > 0;
        Self {
            solid,
            face_count: shell.faces.len(),
            triangle_count,
            triangles,
            retained_brep_source: true,
            lossy_or_preview_mesh: false,
            blockers,
            exact_triangle_mesh_ready,
        }
    }
}

fn triangulate_face<'a, I>(
    _face: BrepFaceId,
    surface: &crate::surface::BrepSurface,
    outer: &[BrepCoedge],
    inner: I,
    edge_by_id: &BTreeMap<crate::topology::BrepEdgeId, BrepEdge>,
    vertex_by_id: &BTreeMap<BrepVertexId, &crate::topology::BrepVertex>,
    blockers: &mut Vec<BrepTriangleMeshBlocker>,
) -> Option<Vec<BrepExactTriangle3>>
where
    I: IntoIterator<Item = &'a [BrepCoedge]>,
{
    if !matches!(surface.kind, BrepSurfaceKind::Plane(_)) {
        blockers.push(BrepTriangleMeshBlocker::SurfaceFrameNotReady);
        return None;
    }
    let frame = surface.frame_report();
    if !frame.exact_frame_ready {
        blockers.push(BrepTriangleMeshBlocker::SurfaceFrameNotReady);
        return None;
    }

    let mut points3 = Vec::new();
    let mut points2 = Vec::new();
    let mut hole_indices = Vec::new();
    push_projected_loop(
        outer,
        surface,
        edge_by_id,
        vertex_by_id,
        blockers,
        &mut points3,
        &mut points2,
    )?;
    for loop_ in inner {
        hole_indices.push(points2.len());
        push_projected_loop(
            loop_,
            surface,
            edge_by_id,
            vertex_by_id,
            blockers,
            &mut points3,
            &mut points2,
        )?;
    }

    let exact = points2
        .iter()
        .map(|point| hypertri::Point2::new(point.x.clone(), point.y.clone()))
        .collect::<Vec<_>>();
    let indices = match hypertri::earcut(&exact, &hole_indices) {
        Ok(indices) => indices,
        Err(_) => {
            blockers.push(BrepTriangleMeshBlocker::TriangulationRejected);
            return None;
        }
    };
    Some(
        indices
            .chunks_exact(3)
            .filter_map(|triangle| {
                Some(BrepExactTriangle3 {
                    vertices: [
                        points3.get(triangle[0])?.clone(),
                        points3.get(triangle[1])?.clone(),
                        points3.get(triangle[2])?.clone(),
                    ],
                })
            })
            .collect(),
    )
}

fn push_projected_loop(
    coedges: &[BrepCoedge],
    surface: &crate::surface::BrepSurface,
    edge_by_id: &BTreeMap<crate::topology::BrepEdgeId, BrepEdge>,
    vertex_by_id: &BTreeMap<BrepVertexId, &crate::topology::BrepVertex>,
    blockers: &mut Vec<BrepTriangleMeshBlocker>,
    points3: &mut Vec<Point3>,
    points2: &mut Vec<Point2>,
) -> Option<()> {
    let vertices = collect_loop_vertices(coedges, edge_by_id, vertex_by_id, blockers)?;
    for point in vertices {
        let projection = surface.project_frame_point(point.clone());
        let Some(uv) = projection.uv else {
            blockers.push(BrepTriangleMeshBlocker::SurfaceFrameNotReady);
            return None;
        };
        points3.push(point);
        points2.push(uv);
    }
    Some(())
}

impl BrepShell {
    /// Replay this retained shell as exact triangle handoff evidence.
    pub fn exact_triangle_mesh_handoff_report(&self) -> BrepExactTriangleMeshHandoffReport {
        BrepExactTriangleMeshHandoffReport::from_shell(self)
    }
}

pub(crate) fn collect_loop_vertices(
    coedges: &[crate::topology::BrepCoedge],
    edge_by_id: &BTreeMap<crate::topology::BrepEdgeId, BrepEdge>,
    vertex_by_id: &BTreeMap<BrepVertexId, &crate::topology::BrepVertex>,
    blockers: &mut Vec<BrepTriangleMeshBlocker>,
) -> Option<Vec<Point3>> {
    if coedges.len() < 3 {
        blockers.push(BrepTriangleMeshBlocker::DegenerateLoop);
        return None;
    }

    let mut starts = Vec::with_capacity(coedges.len());
    let mut ends = Vec::with_capacity(coedges.len());
    for coedge in coedges {
        let Some(edge) = edge_by_id.get(&coedge.edge).copied() else {
            blockers.push(BrepTriangleMeshBlocker::MissingEdge);
            continue;
        };
        if edge.is_degenerate() {
            blockers.push(BrepTriangleMeshBlocker::DegenerateEdge);
        }
        let (start, end) = oriented_endpoints(edge, coedge.orientation);
        starts.push(start);
        ends.push(end);
    }

    if starts.len() != coedges.len() {
        return None;
    }
    for (end, next_start) in ends
        .iter()
        .zip(starts.iter().cycle().skip(1))
        .take(starts.len())
    {
        if end != next_start {
            blockers.push(BrepTriangleMeshBlocker::BrokenLoopChain);
        }
    }

    let mut points = Vec::with_capacity(starts.len());
    for vertex_id in starts {
        let Some(vertex) = vertex_by_id.get(&vertex_id) else {
            blockers.push(BrepTriangleMeshBlocker::MissingVertex);
            continue;
        };
        points.push(vertex.point.clone());
    }
    (points.len() >= 3).then_some(points)
}

fn oriented_endpoints(
    edge: BrepEdge,
    orientation: BrepEdgeOrientation,
) -> (BrepVertexId, BrepVertexId) {
    match orientation {
        BrepEdgeOrientation::Forward => (edge.start, edge.end),
        BrepEdgeOrientation::Reversed => (edge.end, edge.start),
    }
}
